export const ROUTE = {
  HOME: '/',
  THREADS: '/threads',
  NEW_THREAD: '/threads/new',
  THREAD: '/thread',
  PROJECT_THREAD: '/project-thread',
  PROJECTS: '/projects',
  PROJECTS_CREATE: '/projects/create',
  PROJECT_MEMBERS: '/project/members',
  PROJECT_FILES: '/project/files',
  PROJECT_INSTRUCTIONS: '/project/instructions',
  SETTINGS: '/settings',
  GUIDE: '/guide',
  LOGIN: '/login',
} as const;
