export const ROUTE = {
  HOME: '/',
  THREADS: '/threads',
  NEW_THREAD: '/threads/applications',
  THREAD: '/threads/view',
  PROJECT_THREAD: '/project/thread',
  PROJECT_NEW_THREAD: '/project/applications',
  PROJECTS: '/projects',
  PROJECTS_VIEW: '/projects/view',
  PROJECT_MEMBERS: '/project/members',
  PROJECT_FILES: '/project/files',
  PROJECT_INSTRUCTIONS: '/project/instructions',
  SEARCH: '/search',
  SETTINGS: '/settings',
  LOGIN: '/login',
} as const;
