import { test, expect, _electron as electron, ElectronApplication, Page } from '@playwright/test';

async function getFirstWindow(app: ElectronApplication): Promise<Page> {
  const page = await app.firstWindow();
  await page.waitForLoadState('domcontentloaded');
  return page;
}

async function ensureLoggedIn(page: Page) {
  await page.waitForLoadState('networkidle');
  const loginBtn = page.getByRole('button', { name: 'Sign In (Mock)' });
  if (await loginBtn.count()) {
    await expect(loginBtn).toBeVisible({ timeout: 5000 });
    await loginBtn.click();
    await page.waitForTimeout(800);
  }
}

async function ensureProjectCreateForm(page: Page) {
  await page.getByRole('menuitem', { name: 'Projects' }).click();
  const inlineForm = page.locator('form.project-form');
  if (await inlineForm.count()) {
    await expect(inlineForm).toBeVisible({ timeout: 5000 });
    return;
  }
  await page.evaluate(() => {
    globalThis.localStorage?.removeItem('lastProjectId');
    if (globalThis.window) {
      (globalThis.window as any).location.hash = '#/projects';
    }
  });
  await page.waitForTimeout(500);
  await expect(page.locator('form.project-form')).toBeVisible({ timeout: 5000 });
}

async function createProject(page: Page, name: string) {
  await ensureProjectCreateForm(page);
  await page.fill('input#project-name', name);
  const submit = page.locator('form.project-form button.primary').first();
  await expect(submit).toBeVisible({ timeout: 5000 });
  await submit.click();
  await page.waitForTimeout(500);
}

async function createThread(page: Page, title: string) {
  const result = await page.evaluate(async ({ title }) => {
    const api = (globalThis as any).electronAPI ?? (globalThis as any).window?.electronAPI;
    if (!api) return null;
    const res = await api.thread.addUserPrompt(null, 'Autogenerated prompt', {
      title,
    });
    return res.thread.id as string;
  }, { title });
  if (!result) throw new Error('Failed to create thread via API');
  return result;
}

test.describe('E2E: Move thread between projects and general history', () => {
  let app: ElectronApplication | undefined;
  test.describe.configure({ mode: 'serial' });

  test.beforeAll(async () => {
    try {
      const electronExec = (await import('electron')).default as unknown as string;
      app = await electron.launch({ executablePath: electronExec, args: ['.'] });
    } catch {
      try {
        const electronExec = (await import('electron')).default as unknown as string;
        app = await electron.launch({
          executablePath: electronExec,
          args: ['dist-electron/main.js'],
        });
      } catch {
        test.skip(true, 'Electron failed to launch in this environment');
      }
    }
  });

  test.afterAll(async () => {
    if (app) {
      await app.close();
    }
  });

  test('move thread into a project and back to general history', async () => {
    if (!app) throw new Error('Electron not launched');
    const page = await getFirstWindow(app);
    await ensureLoggedIn(page);

    const projectName = `MoveTarget ${Date.now()}`;
    await createProject(page, projectName);

    // Create a thread in general history
    const threadTitle = `Movable Thread ${Date.now()}`;
    await createThread(page, threadTitle);

    await page.reload();
    await ensureLoggedIn(page);

    // Ensure we're on Threads and the header with Move button is visible
    await page.getByRole('menuitem', { name: 'Threads' }).click();
    await expect(page.getByRole('heading', { name: 'Threads', level: 1 })).toBeVisible();

    const sidebar = page.locator('.activity-list-sidebar');
    const threadListItem = sidebar.getByRole('menuitem', { name: threadTitle }).first();
    await expect(threadListItem).toBeVisible({ timeout: 5000 });
    await threadListItem.click();

    // Move button visible
    const moveBtn = page.getByRole('button', { name: 'Move thread to project' });
    await expect(moveBtn).toBeVisible({ timeout: 5000 });
    await moveBtn.click();

    // Move modal appears
    await expect(page.getByRole('heading', { name: 'Move Thread' })).toBeVisible();
    // Select project
    await page.selectOption('#project-select', { label: projectName });
    // Confirm move
    await page
      .locator('.modal-content')
      .getByRole('button', { name: 'Move Thread', exact: true })
      .click();
    // Modal closes
    await expect(page.getByRole('heading', { name: 'Move Thread' })).toHaveCount(0);

    // Sidebar general Threads list should no longer include the moved thread title (if it renders)
    // Navigate to Projects and open the project
    await page.getByRole('menuitem', { name: 'Projects' }).click();
    await page.getByRole('menuitem', { name: projectName }).click();
    // Project detail heading
    await expect(page.getByRole('heading', { name: projectName, level: 1 })).toBeVisible();
    // The project threads section should list our thread title (button with title text)
    const projectThreadList = page.locator('.project-thread-list');
    const projectThreadItem = projectThreadList.getByRole('menuitem', { name: threadTitle }).first();
    await expect(projectThreadItem).toBeVisible({ timeout: 5000 });

    // Click to open the thread in Threads
    await projectThreadItem.click();
    await expect(page.getByRole('heading', { name: 'Threads', level: 1 })).toBeVisible();

    // Move it back to general history
    await expect(moveBtn).toBeVisible({ timeout: 5000 });
    await moveBtn.click();
    await expect(page.getByRole('heading', { name: 'Move Thread' })).toBeVisible();
    // Choose General History
    await page.selectOption('#project-select', { label: 'General History (Unscoped)' });
    await page
      .locator('.modal-content')
      .getByRole('button', { name: 'Move Thread', exact: true })
      .click();
    await expect(page.getByRole('heading', { name: 'Move Thread' })).toHaveCount(0);

    // Verify general history contains the thread again
    // Navigate back to Threads and ensure the page is accessible
    await page.getByRole('menuitem', { name: 'Threads' }).click();
    await expect(page.getByRole('heading', { name: 'Threads', level: 1 })).toBeVisible();
    await expect(sidebar.getByRole('menuitem', { name: threadTitle }).first()).toBeVisible({
      timeout: 5000,
    });
  });
});
