/**
 * Background Prompt types
 * Shared between main process and renderer
 *
 * Background prompts run AI requests in a separate context, invisible to the user's
 * main chat thread. Results are surfaced non-intrusively via UI controls.
 */

/**
 * Types of background prompt tasks
 */
export enum BackgroundPromptType {
  AutoTitle = 'auto-title',
  ContextCompression = 'context-compression',
  InstructionGeneration = 'instruction-generation',
  PromptCoaching = 'prompt-coaching',
}

/**
 * Human-readable display titles for each background prompt type
 */
export function getBackgroundPromptTitle(type: BackgroundPromptType): string {
  const titles: Record<BackgroundPromptType, string> = {
    [BackgroundPromptType.AutoTitle]: 'Title Generation',
    [BackgroundPromptType.ContextCompression]: 'Context Compression',
    [BackgroundPromptType.InstructionGeneration]: 'Instruction Generation',
    [BackgroundPromptType.PromptCoaching]: 'Prompt Coaching',
  };
  return titles[type];
}

/**
 * Priority levels for task scheduling.
 * High-priority tasks are processed before normal and low.
 */
export enum BackgroundPromptPriority {
  High = 'high',
  Normal = 'normal',
  Low = 'low',
}

/**
 * Task status lifecycle
 */
export enum BackgroundPromptStatus {
  Queued = 'queued',
  Running = 'running',
  Completed = 'completed',
  Failed = 'failed',
  Cancelled = 'cancelled',
}

/**
 * Request to submit a background prompt task.
 * Sent from renderer to main process via IPC.
 */
export interface BackgroundPromptRequest {
  /** Unique task identifier (UUID generated by renderer) */
  taskId: string;

  /** Type of background task */
  type: BackgroundPromptType;

  /** Thread ID — used to resolve the agent/model for the prompt */
  threadId: string;

  /** Prompt messages to send to the model */
  messages: { role: string; content: string }[];

  /** Optional system prompt override */
  system?: string;

  /** Optional model override (uses thread's model if omitted) */
  model?: string;

  /** Optional JSON schema for structured output */
  responseFormat?: unknown;

  /** Task priority (defaults to Normal) */
  priority?: BackgroundPromptPriority;

  /** Max tokens for the response */
  maxTokens?: number;

  /** Temperature for generation */
  temperature?: number;
}

/**
 * Result of a completed (or failed/cancelled) background prompt task.
 * Broadcast from main process to renderer via IPC event.
 */
export interface BackgroundPromptResult {
  /** Unique task identifier (matches the request's taskId) */
  taskId: string;

  /** Type of background task */
  type: BackgroundPromptType;

  /** Thread ID this task was associated with */
  threadId: string;

  /** Final status of the task */
  status: BackgroundPromptStatus;

  /** Raw response text from the model */
  result?: string;

  /** Parsed JSON result if responseFormat was used */
  structuredResult?: unknown;

  /** Error message if the task failed */
  error?: string;

  /** Duration of the task in milliseconds */
  durationMs?: number;
}
